name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - run: fastlane scan
    - run: mkdir uploadDir
    - run: echo hello > uploadDir/world.txt  

    - uses: actions/upload-artifact@v2
    with:
    name: my-artifact
    path: uploadDir/world.txt
